relevant_columns : 
- Title
- Author
- Date
- Pages
- Last Edition
- Owned
- Status
- Date Started
- Date Finished
- Days Read
- Pages per Day

column_dtypes:
  Title: str
  Author: str
  Date: str
  Pages: float
  Last Edition: float 
  Owned: str
  Status: str
  Date Started: date
  Date Finished: date
  Days Read: float
  Pages per Day: float

db_name: books.db
